name: "Kotlin Maven CI"

on:
  push:
    branches:
      - main
      - DEV
  pull_request:
    branches:
      - main
      - DEV

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu environment
    
    steps:
      - name: Checkout repository  # Step to check out the repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17  # Step to set up the JDK required for Kotlin
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'  # Use AdoptOpenJDK
          java-version: '17'  # Ensure this matches your project setup

      - name: Cache Maven packages  # Optional: Cache Maven dependencies to speed up builds
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven  # Step to build the project using Maven
        run: mvn -B package --file pom.xml  # -B is batch mode for non-interactive builds

      - name: Run tests  # Step to run unit tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # The 'deploy' job will only run if the 'build' job succeeds
    if: github.ref == 'refs/heads/main'  # Deploy only from the 'main' branch
    steps:
      - name: Deploy application
        run: echo "Deploying Kotlin Maven application..."
